### PR TITLE
IBM UrbanCode Standards Update

### PR DESCRIPTION
**Pull request by nhmathis**
- Major restructuring of files and folders
- Added build.xml (Can now build with command: 'ant')
- Added ivy.xml for dependency management
- All scripts now use groovy-plugin-utils
- Updated all step names

### CODE REVIEW

**Comment by nhmathis** [comment]
Thank you for your submission! You'll find my immediate changes above. 

Once merged, it would be appreciated if you could write a little documentation on how you use the plugin and confirm/update step and property name and descriptions. 

Thanks!

- Nick

**Comment by nhmathis** [comment]
@fewproud 

Are you able to accept my pull request and confirm the plugin is still in a working state?

Nick

**Comment by fewproud** [comment]
@nhmathis sorry, I missed you previous message. I will have a look today. Thanks

**Comment by fewproud** [comment]
@nhmathis 
Sorry I'm not too familiar with GitHub, I don't know how to pull your change. I just review it and think it is still in working state. Is it right?

Thank you.

**Comment by nhmathis** [comment]
Hi @fewproud,

You will need to merge the pull request for the changes to take effect. There should be a button above this comment.

- Nick

**Comment by nhmathis** [comment]
After the changes are merged (or before), I would appreciate it if you could compile it and give it a quick test run.

**Comment by fewproud** [comment]
@nhmathis 
Why I always got an error message when I run the build.xml?

_BUILD FAILED
/Users/fanhu/Documents/workspace/AnsibleUCDPlugin/build.xml:195: Please run the build again.
Note: If you get this message more than once, trying specify your Ant's home directory with the flag: ant -DantHome='ant/home/directory/here' or set/export the `ANT_HOME` environment variable._

Is it normal?

Thanks

**Comment by nhmathis** [comment]
Hi @fewproud,

The project builds with `ant` and references your `ANT_HOME` for the location of the installation folder. If you do not have ant installed, please download it here: http://ant.apache.org/manual/install.html

Once installed, follow the directions to set your `ANT_HOME` environment variable. Otherwise if you already have `ant` installed, follow the step #4 on the short story directions there on how to set `ANT_HOME`. 

Previously, the project was "compiled" by simply moving the all files into a zip. As we build the plugin out, we wouldn't be able to resolve dependencies and correctly place class files without it. Having a build script solves that need and prevents any special build scenarios by standardizing the process for everyone.

Let me know if you have any other questions. 

-Nick

**Comment by fewproud** [comment]
Hi @nhmathis 

Thanks for the information. I have built it and have some brief testing, it looks it's working.

Last time you mentioned the documentation. Where I shall write the document?

Thanks

**Comment by nhmathis** [comment]
Hi @fewproud

Thanks for merging in the changes! I'm going to fork this repository on our main GitHub org. After that, you can delete this repo and make all future changes at this new repo.

I think the best place to put the documentation would be on the GitHub Wiki. You'll find a Wiki tab on the top of the repository. Just write all your documentation there. Here's a GitHub wiki guide: https://guides.github.com/features/wikis/

I'll post the new repo soon and grant you access. 

- Nick

**Comment by nhmathis** [comment]
New Repository: https://github.com/IBM-UrbanCode/Ansible-Toolkit-UCD
I've granted you access to the new repository. Please confirm. Once accepted, you should then delete this repo so our IBM-UrbanCode repo becomes the master.

**Pull request merged**
